name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIV_KEY }}
        port: 22
        script: |
          cd ~/home/ubuntu/crypto_alerts
          git pull origin master
          git status
          sudo docker build --pull --rm -f "DockerFile" -t cryptoalerts:latest "."
          sudo docker run -p 3000:3000 cryptoalerts
