name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        port: 22
        script: |
          cd crypto_alerts
          git pull
          git status
          sudo sh ./docker_stop.sh
          sudo docker build --pull --rm -f "Dockerfile" -t cryptoalerts:latest "."
          sudo docker run -d -p 3000:3000 cryptoalerts
